### ISSUE TITLE
Disable screen saver / power save mode

### ISSUE THREAD

**Issue by falue** [aronsommer/eddy-g#22]
As I cannot figure out how to do this in the browser - maybe try it in the app?

https://www.electronjs.org/docs/latest/api/power-save-blocker

**Comment by aronsommer** [comment]
added in new build but needs testing

**Comment by falue** [comment]
will do!

**Comment by falue** [comment]
Disabling screen saver works,
Disabling poer sleep does not.
I guess its solved as this is how far we can go on this? Close if you think alike.
